version: '2'
services:
  ktt_mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './mariadb_data:/bitnami'
  ktt_opencart:
    image: 'bitnami/opencart:3'
    environment:
      - MARIADB_HOST=ktt_mariadb
      - MARIADB_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - OPENCART_HOST=localhost
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '81:80'
      - '443:443'
    volumes:
      - './opencart_data:/bitnami'
    depends_on:
      - ktt_mariadb
  ktt_phpmyadmin:
    image: 'bitnami/phpmyadmin:4'
    ports:
      - '82:80'
      - '444:443'
    depends_on:
      - ktt_mariadb
    volumes:
      - './phpmyadmin_data:/bitnami'
volumes:
  ktt_mariadb_data:
    driver: local
  ktt_opencart_data:
    driver: local
  ktt_phpmyadmin_data:
    driver: local