version: '3.7'

services:
  ktt_php:
    build: ./docker/php
    container_name: ktt_php
    volumes:
      - .:/var/www/html
      - /tmp:/tmp
      - ~/.composer:/var/www/.composer
    depends_on:
      - ktt_mysql
    networks:
      - ktt-net

  ktt_mysql:
    image: mysql:5.7
    container_name: ktt_mysql
    ports:
      - "3386:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kttdb
      - MYSQL_USER=opencart
      - MYSQL_PASSWORD=root
    volumes:
      - ktt_mysql_data:/var/lib/mysql
    networks:
      - ktt-net

  ktt_opencart:
    build: ./docker/opencart
    container_name: ktt_opencart
    restart: always
    ports:
      - '86:80'
      - '446:443'
    volumes:
      - ./public:/var/www/html
    depends_on:
      - ktt_mysql
    networks:
      - ktt-net

  ktt_pma:
    image: phpmyadmin/phpmyadmin
    container_name: ktt_pma
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8086:80
    volumes:
      - /sessions
    depends_on:
      - ktt_mysql
    networks:
      - ktt-net

networks:
  ktt-net:

volumes:
  ktt_mysql_data:

